name: swim_apps_shared
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  cloud_firestore:
  firebase_auth:
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.3
  intl: ^0.20.2
  provider: ^6.1.2 # Added provider
  cloud_functions: ^6.0.4
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_cloud_firestore: ^4.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.8
